# Source: jenkins-resources/templates/pipelineactivity-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-pipeline-activity
  namespace: myjenkins
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-pipeline-activity
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: myjenkins
