filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
releases:
- chart: dev/jx3-walk-go
  version: 0.0.1
  name: jx3-walk-go
  values:
  - jx-values.yaml
- chart: dev/jx3-golang1
  version: 0.0.3
  name: jx3-golang1
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
