# Source: jx3-golang1/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-20T16:28:52Z"
  deletionTimestamp: null
  name: 'jx3-golang1-0.0.4'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.4
      sha: b6e83411024f697d125b7c3b020fcd841711cb4f
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: c53381879bc1a1b8a2566172d3779bc35eecf9dc
    - author:
        email: rawlingsj80@gmail.com
        name: James Rawlings
      branch: master
      committer:
        email: rawlingsj80@gmail.com
        name: James Rawlings
      message: |
        chore: add secret
      sha: 3d4957512b78e38c8aeb990b946f5c178074b348
  gitHttpUrl: https://github.com/cb-kubecd/jx3-golang1
  gitOwner: cb-kubecd
  gitRepository: jx3-golang1
  name: 'jx3-golang1'
  releaseNotesURL: https://github.com/cb-kubecd/jx3-golang1/releases/tag/v0.0.4
  version: v0.0.4
status: {}
