# Source: jx3-golang1/templates/sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx3-golang1-jx3-golang1
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
