apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        cb-kubecd/jx3-demo-walk-cluster: true
        cb-kubecd/jx3-golang-demo: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        cb-kubecd/jx3-demo-walk-cluster: merge
        cb-kubecd/jx3-golang-demo: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - cb-kubecd/jx3-demo-walk-cluster
        - cb-kubecd/jx3-golang-demo
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - cb-kubecd/jx3-demo-walk-cluster
        - cb-kubecd/jx3-golang-demo
      target_url: http://dashboard-jx.walk.jenkinsxlabs.com
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
