# Source: jx-kh-check/templates/jx-webhook-events-check.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jx-webhook-events-check-rb
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jx-webhook-events-service-role
subjects:
  - kind: ServiceAccount
    name: jx-webhook-events-sa
    namespace: jx
