filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://charts.helm.sh/stable
- name: grafana
  url: https://grafana.github.io/helm-charts
releases:
- chart: bitnami/external-dns
  version: 4.5.0
  condition: jxRequirementsIngressExternalDNS.enabled
  name: external-dns
  values:
  - ../../versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/acme
  version: 0.0.19
  condition: jxRequirementsIngressTLS.enabled
  name: acme-jx
  values:
  - ../../versionStream/charts/jx3/acme-jx/values.yaml.gotmpl
  - jx-values.yaml
- chart: jenkins-x/jxboot-helmfile-resources
  version: 1.0.27
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jenkins-x-crds
  version: 3.0.5
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jx-pipelines-visualizer
  version: 1.1.2
  name: jx-pipelines-visualizer
  values:
  - ../../versionStream/charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jx-preview
  version: 0.0.144
  name: jx-preview
  values:
  - jx-values.yaml
- chart: jenkins-x/lighthouse
  version: 0.0.918
  name: lighthouse
  values:
  - ../../versionStream/charts/jenkins-x/lighthouse/values.yaml.gotmpl
  - jx-values.yaml
- chart: jenkins-x/nexus
  version: 0.1.37
  name: nexus
  values:
  - ../../versionStream/charts/jenkins-x/nexus/values.yaml.gotmpl
  - jx-values.yaml
- chart: stable/chartmuseum
  version: 2.14.2
  name: chartmuseum
  values:
  - ../../versionStream/charts/stable/chartmuseum/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jx-build-controller
  version: 0.0.27
  name: jx-build-controller
  values:
  - ../../versionStream/charts/jx3/jx-build-controller/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jx-kh-check
  version: 0.0.56
  condition: jxRequirementsKuberhealthy.enabled
  name: health-checks-jx
  values:
  - ../../versionStream/charts/jx3/health-checks-jx/values.yaml.gotmpl
  - jx-values.yaml
- chart: grafana/grafana
  version: 6.4.2
  name: grafana
  values:
  - ../../versionStream/charts/grafana/grafana/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
